### ISSUE TITLE
trouble with reading

### ISSUE THREAD

**Issue by tomasvida** [fucm/node-red#5]
Hello,
I installed ServiceWelt Tecalor flow, configured my ISG and I can't get through this error in the CONVERT To NUMBER cell with this error message:
14. 1. 2022 21:58:19node: Convert to number
msg : string[73]
"Invalid JSONata expression: Unable to cast value to a number: "87.496kWh""
I also tried the variant where I exchanged the dot for a comma in the number, but it ends with the same error voice.
Can you help me, please?
Tnx. Tomas

**Comment by fucm** [comment]
Hi, @hth2 did contribute the Tecalor flows. Could you help here?

**Comment by tomasvida** [comment]
Hi, I found that one of my problems will be the missing space between the number and °C. Unfortunately, I don't know how to fix it in flow.

![image](https://user-images.githubusercontent.com/97637008/151677518-5d68c992-076c-49bc-a24f-fa0350a8ec18.png)

**Comment by fucm** [comment]
Hi, I don't know how much @hth2 did take over from my original flow, but you have to look for the node called "Convert to number" and open it. My node looks like this:
![image](https://user-images.githubusercontent.com/39280548/151677647-f5598043-00c4-479d-adb4-e2bb2f93c8fd.png)

Try changing `$substringBefore(payload[0], ' ')` to `$substringBefore(payload[0], '°C')`

**Comment by ronbigb** [comment]
I had the same problem but managed to avoid it by opening the node mentioned by fucm and adding an additional change block where i searched for °C and replaced it with nothing.

**Comment by fucm** [comment]
Thanks for the recommendation
